spring:
  ##JPA配置
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql

  ##Druid数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    ###################以下为druid增加的配置###########################
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    ###############以上为配置druid添加的配置########################################

  ##添加对jsp支持配置
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  ##热部署配置
  devtools:
    restart:
      ##热部署配置生效
      enabled: true
      ##该路径下的文件修改后会restart
      additional-paths: src/main/java

##myabtis配置
mybatis:
  ##扫描xml文件
  mapper-locations: classpath:com/liuzw/common/mapper/*.xml
  ##设置别名
  type-aliases-package: com.liuzw.common.vo,com.liuzw.common.entity

##pagehelper配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

##swagger配置
swagger:
  flag: true





